<?php
date_default_timezone_set('Asia/Kuala_Lumpur');
$now=date("Y-m-d H:i:s");
//file_put_contents('debug1.log',var_export($now,1));
//$mysqli = new mysqli("localhost", "fbsonline", "30Fu45y7qjsH9dze", "fbsonline");
//$mysqli = new mysqli("localhost", "my369forex", "30Fu45y7qjsH9dze", "my369forex");
$mysqli = new mysqli("mysql", "root", "CF26D23C453D3EB6", "my369forex");
if(isset($_POST['result']))$result=$_POST['result'];
$aresult=explode('*',$result);
$arst=explode('|',$aresult[0]);
//file_put_contents('debug1.log',var_export($arst,1));
if(count($arst)>4){
    $sql="update AdjCs28 set ";
    $sql.="d100min={$arst[1]},d100max={$arst[2]},";
    $sql.="d100adjmin={$arst[3]},d100adjmax={$arst[4]},";
    $sql.="priceclose={$arst[5]},pospct={$arst[6]},";
    $sql.="d5adjmin={$arst[7]},d5adjmax={$arst[8]},";
    $sql.="d5pospct={$arst[9]},";
    $sql.="pcth1={$arst[10]},";
    $sql.="pcth2={$arst[11]},";
    $sql.="pcth4={$arst[12]},";
    $sql.="pcth8={$arst[13]},";
    $sql.="pcth12={$arst[14]},";
    $sql.="pcth16={$arst[15]},";
    $sql.="pcth20={$arst[16]},";
    $sql.="pcth24={$arst[17]},";
    $sql.="pctd5={$arst[18]},";
    $sql.="pctd10={$arst[19]},";
    $sql.="pctd20={$arst[20]},";
    $sql.="pctd30={$arst[21]},";
    $sql.="pctd60={$arst[22]},";
    $sql.="pctd100={$arst[23]},";
    $sql.="pctd200={$arst[24]},";
    $sql.="pctd300={$arst[25]},";
    $sql.="m5CrossCount={$arst[26]},";
    $sql.="pipsh4={$arst[27]},";
    $sql.="pipsh24={$arst[28]},";
	$sql.="pipsd5={$arst[34]},";
	$sql.="pipsd10={$arst[35]},";
    $sql.="h1CrossCount={$arst[29]},";
	$sql.="pctm120={$arst[30]},";
	$sql.="pipsh1={$arst[31]},";
    if($arst[36]>0)$sql.="avrgh1={$arst[36]},";
    if($arst[37]<>0)$sql.="heighth1={$arst[37]},";
    if($arst[38]>0)$sql.="avrghh1={$arst[38]},";
    if($arst[39]<>0)$sql.="heightd1={$arst[39]},";
    if($arst[40]>0)$sql.="avrgd1={$arst[40]},";
    if($arst[41]<>0)$sql.="d30MinPrice={$arst[41]},";
    if($arst[42]>0)$sql.="d30MaxPrice={$arst[42]},";
    if($arst[43]>0)$sql.="MaxM60U={$arst[43]},";
    if($arst[44]>0)$sql.="MaxM60D={$arst[44]},";
	$sql.="m1pipsdown60={$arst[32]},";
	$sql.="m1pipsup60={$arst[33]},";
    $sql.="lastupdate='{$now}'";
    $sql.=" where pair='{$arst[0]}'";
    //file_put_contents('debug.log',$sql);
    $mysqli->query($sql);
}